#!/bin/bash
# =============================================================================
# CodeHaat - Interactive Setup (AGUI / TUI Edition)
# =============================================================================
set -e

# ── Colors ──
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

# Clear screen and show ASCII Art
clear
echo -e "${CYAN}"
cat << "EOF"
   ____          _      _   _             _   
  / ___|___   __| | ___| | | | __ _  __ _| |_ 
 | |   / _ \ / _` |/ _ \ |_| |/ _` |/ _` | __|
 | |__| (_) | (_| |  __/  _  | (_| | (_| | |_ 
  \____\___/ \__,_|\___|_| |_|\__,_|\__,_|\__|
                                              
EOF
echo -e "${NC}"
echo -e "${GREEN}  🚀 Starting AGUI Setup Environment...${NC}\n"

# ── Check Docker ──
if ! command -v docker &> /dev/null; then
    if command -v whiptail &> /dev/null; then
        whiptail --title "Error" --msgbox "Docker not found! Please install Docker first." 8 45
    else
        echo -e "${RED}✗ Docker not found. Install Docker first.${NC}"
    fi
    exit 1
fi

if ! docker compose version &> /dev/null; then
    if command -v whiptail &> /dev/null; then
        whiptail --title "Error" --msgbox "Docker Compose not found!" 8 45
    else
        echo -e "${RED}✗ Docker Compose not found.${NC}"
    fi
    exit 1
fi

# Function for GUI Input
get_input() {
    local title="$1"
    local text="$2"
    local var_name="$3"
    
    if command -v whiptail &> /dev/null; then
        local result=$(whiptail --title "$title" --inputbox "$text" 10 60 3>&1 1>&2 2>&3)
        eval $var_name="'$result'"
    else
        read -p "$text: " result
        eval $var_name="'$result'"
    fi
}

# ── Ask for API Keys using GUI ──
if command -v whiptail &> /dev/null; then
    whiptail --title "CodeHaat Setup" --msgbox "Welcome to CodeHaat!\nWe need to configure a few API keys to get your environment ready." 10 60
fi

get_input "Razorpay Config" "Enter Razorpay Key ID (rzp_test_xxxxx):" RZP_KEY_ID
get_input "Razorpay Config" "Enter Razorpay Key Secret:" RZP_KEY_SECRET

get_input "GitHub OAuth Config" "Enter GitHub Client ID (Ov23li...):" GH_CLIENT_ID
get_input "GitHub OAuth Config" "Enter GitHub Client Secret:" GH_CLIENT_SECRET

# ── Generate secure random secrets ──
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '\n/+=' | head -c 64)
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | head -c 32)
REDIS_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | head -c 32)

# ── Write .env ──
if command -v whiptail &> /dev/null; then
    whiptail --title "Configuration" --infobox "Generating secure secrets and writing .env file..." 8 60
else
    echo -e "${CYAN}Generating secure secrets and writing .env file...${NC}"
fi

cat > .env << EOF
# CodeHaat Environment - Generated by Setup AGUI
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Razorpay Payment Gateway
RAZORPAY_KEY_ID=${RZP_KEY_ID}
RAZORPAY_KEY_SECRET=${RZP_KEY_SECRET}

# GitHub OAuth
GITHUB_CLIENT_ID=${GH_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GH_CLIENT_SECRET}
NEXT_PUBLIC_GITHUB_CLIENT_ID=${GH_CLIENT_ID}

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}
EOF

sleep 1

# ── Build and start Docker ──
if command -v whiptail &> /dev/null; then
    whiptail --title "Docker Initialization" --infobox "Building and starting Docker services.\nThis will run in the background, please wait..." 10 60
else
    echo -e "${CYAN}Building and starting services...${NC}"
fi

# Run docker compose
docker compose up -d --build

# ── Wait for services ──
echo -e "${CYAN}Waiting for backend to be ready...${NC}"
MAX_WAIT=60
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    if curl -sf http://localhost:4001/health > /dev/null 2>&1; then
        break
    fi
    sleep 2
    WAITED=$((WAITED + 2))
    printf "."
done
echo ""

# ── Finish Setup ──
if command -v whiptail &> /dev/null; then
    whiptail --title "Setup Complete!" --msgbox "CodeHaat is successfully running!\n\n🌐 Frontend: http://localhost:3000\n⚙️  Backend:  http://localhost:4001" 10 50
else
    echo ""
    echo -e "${GREEN}  ╔══════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}  ║         ✅ Setup Complete!               ║${NC}"
    echo -e "${GREEN}  ╠══════════════════════════════════════════╣${NC}"
    echo -e "${GREEN}  ║                                          ║${NC}"
    echo -e "${GREEN}  ║  Frontend:  http://localhost:3000         ║${NC}"
    echo -e "${GREEN}  ║  Backend:   http://localhost:4001         ║${NC}"
    echo -e "${GREEN}  ║                                          ║${NC}"
    echo -e "${GREEN}  ╚══════════════════════════════════════════╝${NC}"
    echo ""
fi

