#!/bin/bash
# =============================================================================
# CodeHaat - Interactive Setup
# =============================================================================
set -e

clear
echo ""
echo "  ╔══════════════════════════════════════════╗"
echo "  ║         🚀 CodeHaat Setup                ║"
echo "  ╚══════════════════════════════════════════╝"
echo ""

# ── Colors ──
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

# ── Check Docker ──
if ! command -v docker &> /dev/null; then
    echo -e "${RED}✗ Docker not found. Install Docker first.${NC}"
    echo "  https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}✗ Docker Compose not found.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Docker found${NC}"
echo ""

# ── Create .env ──
if [ -f .env ]; then
    echo -e "${YELLOW}⚠ .env already exists. Overwriting...${NC}"
fi

# ── Ask for Razorpay keys ──
echo -e "${CYAN}┌─────────────────────────────────────────┐${NC}"
echo -e "${CYAN}│  Razorpay Payment Gateway Setup         │${NC}"
echo -e "${CYAN}│  Get keys from: dashboard.razorpay.com  │${NC}"
echo -e "${CYAN}└─────────────────────────────────────────┘${NC}"
echo ""
read -p "  Razorpay Key ID (rzp_test_xxxxx): " RZP_KEY_ID
read -p "  Razorpay Key Secret: " RZP_KEY_SECRET
echo ""

# ── Validate Razorpay keys ──
if [ -z "$RZP_KEY_ID" ] || [ -z "$RZP_KEY_SECRET" ]; then
    echo -e "${YELLOW}⚠ No Razorpay keys provided. Payment features will be disabled.${NC}"
    echo ""
fi

# ── Ask for GitHub OAuth keys ──
echo -e "${CYAN}┌─────────────────────────────────────────┐${NC}"
echo -e "${CYAN}│  GitHub OAuth Setup                     │${NC}"
echo -e "${CYAN}│  Create app: github.com/settings/apps   │${NC}"
echo -e "${CYAN}│  Callback URL: localhost:3000/api/auth/ │${NC}"
echo -e "${CYAN}│                callback                 │${NC}"
echo -e "${CYAN}└─────────────────────────────────────────┘${NC}"
echo ""
read -p "  GitHub Client ID (Ov23li...): " GH_CLIENT_ID
read -p "  GitHub Client Secret: " GH_CLIENT_SECRET
echo ""

# ── Validate GitHub keys ──
if [ -z "$GH_CLIENT_ID" ] || [ -z "$GH_CLIENT_SECRET" ]; then
    echo -e "${YELLOW}⚠ No GitHub keys provided. GitHub login will be disabled.${NC}"
    echo ""
fi

# ── Generate secure random secrets ──
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '\n/+=' | head -c 64)
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | head -c 32)
REDIS_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | head -c 32)

# ── Write .env ──
cat > .env << EOF
# CodeHaat Environment - Generated by setup.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Razorpay Payment Gateway
RAZORPAY_KEY_ID=${RZP_KEY_ID}
RAZORPAY_KEY_SECRET=${RZP_KEY_SECRET}

# GitHub OAuth
# (NEXT_PUBLIC_GITHUB_CLIENT_ID = same as GITHUB_CLIENT_ID; it's public, baked at build time)
GITHUB_CLIENT_ID=${GH_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GH_CLIENT_SECRET}
NEXT_PUBLIC_GITHUB_CLIENT_ID=${GH_CLIENT_ID}

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}
EOF

echo -e "${GREEN}✓ .env created with secure secrets${NC}"
echo ""

# ── Build and start Docker ──
echo -e "${CYAN}Building and starting services...${NC}"
echo ""

docker compose up -d --build

# ── Wait for services ──
echo ""
echo -e "${CYAN}Waiting for services to be ready...${NC}"

MAX_WAIT=60
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    if curl -sf http://localhost:4001/health > /dev/null 2>&1; then
        break
    fi
    sleep 2
    WAITED=$((WAITED + 2))
    printf "."
done
echo ""

# ── Check status ──
if curl -sf http://localhost:4001/health > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Backend is ready${NC}"
else
    echo -e "${YELLOW}⚠ Backend may still be starting...${NC}"
fi

echo ""
echo "  ╔══════════════════════════════════════════╗"
echo "  ║         ✅ Setup Complete!               ║"
echo "  ╠══════════════════════════════════════════╣"
echo "  ║                                          ║"
echo "  ║  Frontend:  http://localhost:3000         ║"
echo "  ║  Backend:   http://localhost:4001         ║"
echo "  ║                                          ║"
echo "  ╚══════════════════════════════════════════╝"
echo ""
