"use client";

import React, { useState, useRef } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

export default function Verify2FAPage() {
  const [digits, setDigits] = useState<string[]>(["", "", "", "", "", ""]);
  const [useBackupCode, setUseBackupCode] = useState(false);
  const [backupKey, setBackupKey] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isSuccess, setIsSuccess] = useState(false);

  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  const handleDigitChange = (index: number, value: string) => {
    // Handle only numeric input
    const cleanVal = value.replace(/\D/g, "");
    if (!cleanVal && value !== "") return;

    const newDigits = [...digits];
    newDigits[index] = cleanVal ? cleanVal[cleanVal.length - 1] : "";
    setDigits(newDigits);

    // Auto-advance
    if (cleanVal && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !digits[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pasted = e.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6);
    if (!pasted) return;

    const newDigits = [...digits];
    for (let i = 0; i < 6; i++) {
      newDigits[i] = pasted[i] || "";
    }
    setDigits(newDigits);
    const nextEmpty = newDigits.findIndex((d) => !d);
    if (nextEmpty !== -1) {
      inputRefs.current[nextEmpty]?.focus();
    } else {
      inputRefs.current[5]?.focus();
    }
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setErrorMessage(null);

    const code = digits.join("");
    if (!useBackupCode && code.length < 6) {
      setErrorMessage("Please enter all 6 digits of your authenticator code.");
      return;
    }
    if (useBackupCode && !backupKey.trim()) {
      setErrorMessage("Please enter a valid backup recovery key.");
      return;
    }

    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      setIsSuccess(true);
    }, 1200);
  };

  if (isSuccess) {
    return (
      <div className="w-full text-center py-6">
        <div className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto mb-5 text-emerald-400 shadow-[0_0_25px_rgba(16,185,129,0.2)]">
          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
          </svg>
        </div>
        <Badge variant="success" className="mb-2 font-mono">
          Session Authenticated
        </Badge>
        <h2 className="text-2xl font-bold font-heading text-white">Vault Access Granted</h2>
        <p className="text-sm text-[#A1A1AA] mt-2 max-w-sm mx-auto">
          Your RFC 6238 TOTP token was cryptographically validated. Initializing secure escrow dashboard...
        </p>
        <div className="mt-8">
          <Link href="/">
            <Button className="w-full h-11 rounded-xl bg-gradient-to-r from-[#8535FC] to-[#6A1BEE] hover:from-[#7822FA] hover:to-[#5E12E0] shadow-[0_0_20px_rgba(133,53,252,0.35)]">
              Enter KodeDock Marketplace →
            </Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full">
      {/* Header */}
      <div className="mb-6">
        <Link
          href="/login"
          className="inline-flex items-center gap-1.5 text-xs text-[#A1A1AA] hover:text-[#8535FC] transition-colors mb-4"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
          </svg>
          <span>Back to Sign In</span>
        </Link>
        <div className="flex items-center justify-between">
          <h2 className="text-2xl sm:text-3xl font-bold font-heading text-white tracking-tight">
            Two-Factor Auth
          </h2>
          <Badge variant="violet" className="font-mono text-[11px]">
            RFC 6238
          </Badge>
        </div>
        <p className="text-sm text-[#A1A1AA] mt-2">
          Enter the 6-digit dynamic passcode generated by your authenticator app (Google Authenticator, Authy, 1Password).
        </p>
      </div>

      {/* Error Banner */}
      {errorMessage && (
        <div className="mb-5 p-3.5 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400 text-xs flex items-center gap-2.5">
          <svg className="w-4 h-4 shrink-0" fill="currentColor" viewBox="0 0 20 20">
            <path
              fillRule="evenodd"
              d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z"
              clipRule="evenodd"
            />
          </svg>
          <span>{errorMessage}</span>
        </div>
      )}

      {/* Form */}
      <form
        method="POST"
        action="#"
        onSubmit={handleSubmit}
        className="space-y-6"
        noValidate
      >
        {!useBackupCode ? (
          <div>
            <label className="block text-xs font-mono uppercase tracking-wider text-[#A1A1AA] mb-3 text-center">
              6-Digit Authenticator Token
            </label>
            <div className="flex items-center justify-center gap-2 sm:gap-3" onPaste={handlePaste}>
              {digits.map((digit, index) => (
                <input
                  key={index}
                  ref={(el) => {
                    inputRefs.current[index] = el;
                  }}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={1}
                  value={digit}
                  onChange={(e) => handleDigitChange(index, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(index, e)}
                  className="w-11 h-13 sm:w-12 sm:h-14 text-center font-mono text-xl font-bold rounded-xl border border-[#414146]/70 bg-[#141417] text-white shadow-inner focus:outline-none focus:ring-2 focus:ring-[#8535FC]/50 focus:border-[#8535FC] transition-all"
                  autoFocus={index === 0}
                />
              ))}
            </div>
          </div>
        ) : (
          <div>
            <label className="block text-xs font-medium text-[#EDEDF0] mb-1.5 font-sans">
              16-Character Vault Recovery Key
            </label>
            <Input
              type="text"
              placeholder="KD-SEC-XXXX-XXXX-XXXX"
              value={backupKey}
              onChange={(e) => setBackupKey(e.target.value)}
              className="font-mono uppercase tracking-wider text-center"
              required
            />
          </div>
        )}

        {/* Switch Between TOTP and Backup Key */}
        <div className="flex items-center justify-between text-xs pt-1">
          <button
            type="button"
            onClick={() => {
              setUseBackupCode(!useBackupCode);
              setErrorMessage(null);
            }}
            className="text-purple-300 hover:text-purple-200 transition-colors font-medium underline-offset-4 hover:underline cursor-pointer"
          >
            {useBackupCode ? "Use 6-digit TOTP app instead" : "Use backup recovery key"}
          </button>

          <span className="text-[11px] font-mono text-emerald-400/90 flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
            Hardware Shield
          </span>
        </div>

        {/* Submit */}
        <Button
          type="submit"
          disabled={isLoading}
          className="w-full h-11 text-sm font-semibold rounded-xl bg-gradient-to-r from-[#8535FC] to-[#6A1BEE] hover:from-[#7822FA] hover:to-[#5E12E0] shadow-[0_0_20px_rgba(133,53,252,0.35)] transition-all cursor-pointer"
        >
          {isLoading ? (
            <div className="flex items-center gap-2">
              <svg className="animate-spin h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              <span>Validating Time-Based Token...</span>
            </div>
          ) : (
            <span>Verify & Authorize Vault</span>
          )}
        </Button>
      </form>
    </div>
  );
}
