name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important to allow the bot to commit changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore(contributors): auto-update contributors list"
          readme_path: "README.md,CONTRIBUTING.md"
